### PR TITLE
Add a GenericFileFetch for more generic files that implements FetchInterface

### PR DESCRIPTION
**Pull request by Algomorph**
- The utility allows to process much generic RGB & depth frame filenames (for alternative datasets to VolumeDeform)
- If mask images are present in the folder, the utility will also apply masks to both depth & RGB images while fetching (for sequences like the ones in the KillingFusion/SobolevFusion dataset).
- Separates out FetchInterface and everything that implements it into a separate folder & source group, still under imgproc
- Refactors FileFetch to VolumeDeformFileFetch to make its purpose more clear
- Replaces use of VolumeDeformFileFetch with the use of GenericFileFetch within the SurfelWarpSerial class.

### CODE REVIEW

**Comment by weigao95** [comment]
I run into index out of range error. It seems the fetcher wants to load offline computed foreground mask even though it is not requested to.
Capture

**Comment by Algomorph** [comment]
Ah, yes, I didn't check for this. I'll fix shortly.

**Comment by Algomorph** [comment]
@weigao95 , I made a simple logic mistake with the mask usage flag, sorry about this. It's fixed now. I tested on a couple of the VolumeDeform sequences, as well as the Killing/Sobolev Fusion Snoopy sequence.
Please, take a look.

**Comment by XuelianCheng** [comment]
@Algomorph  hi, I have tried to run the code with the **offline masks** of Killing/SobolevFusion Duck sequence. However, it reports the error 'terminate called after throwing an instance of 'std::runtime_error*'' like below:
image

Here is the config file:
image

I am not sure if the configs are correctly set. Could you help to check?

**Comment by Algomorph** [comment]
@XuelianCheng sorry, I am unable to dedicate time to maintaining this codebase at this time. Maybe the actual maintaner & author, @weigao95, can be of more help.

**Comment by XuelianCheng** [comment]
Thanks @Algomorph!

I have changed the boundary_clip to 0 in common/global_configs.h, and the results show offline mask is correctly on the image. However, it seems the utility still uses the mask generated by the build-in segmentation algorithm on depth map and rendered images, see the screenshot:

image


@weigao95 Is there any suggestion for this? Many thanks!

**Pull request merged**
